version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  mysql:
    image: mysql:5.7
    container_name: base_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_HOST: "localhost"
    ports:
      - ${DB_PORT}:3306
    networks:
      - web
      - internal

  postgres:
    image: postgres:12.4
    container_name: base_postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    networks:
      - web
      - internal

