test-backoffice:
  stage: test
  image: buildkite/puppeteer:v1.10.0
  only: &changes
    refs:
      - merge_requests
      - master
      - develop
    changes:
      - backoffice/**/*
  script:
    - cd backoffice
    - npm install
    - npm run build

deploy-backoffice:
  image: ruby:2.6
  stage: deploy
  script:
    - cd backoffice
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_BACKOFFICE_PRODUCTION --api-key=$HEROKU_PRODUCTION_API_KEY
  only: &changes
    refs:
      - develop
    changes:
      - backoffice/**/*
